version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /apps/web
    schedule: { interval: weekly }
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: /packages/api-client
    schedule: { interval: weekly }
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /services/edge
    schedule: { interval: weekly }
    open-pull-requests-limit: 3
