[package]
name = "assetlibrary-telemetry"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
http = "1"
metrics = "0.24.6"
metrics-exporter-prometheus = { version = "0.18.3", default-features = false, features = ["http-listener"] }
opentelemetry = "0.33.0"
opentelemetry-otlp = { version = "0.33.0", default-features = false, features = ["http-proto", "reqwest-blocking-client", "trace"] }
opentelemetry_sdk = "0.33.0"
sqlx = { version = "0.8", default-features = false, features = ["postgres", "runtime-tokio-rustls"] }
tokio = { version = "1", features = ["rt", "time"] }
tracing = "0.1"
tracing-opentelemetry = "0.34.0"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
